### ISSUE TITLE
Delphi and C++Builder visibility on GitHub and outside

### ISSUE THREAD

**Issue by DeveloppeurPascal** [Embarcadero/RADStudio12Demos#3]
Hi

Just a notice to remember you to add some topics on this repository like you did for https://github.com/Embarcadero/RADStudio11Demos

https://github.com/topics/delphi-sample and https://github.com/topics/cpp-samples need you too ;-)

**Comment by jimmckeeth** [comment]
Good suggestion! Done.

**Comment by DeveloppeurPascal** [comment]
Thanks Jim ;)
