### ISSUE TITLE
Looks like the encrypted SQLite sample is missing

### ISSUE THREAD

**Issue by PeterAdam** [Embarcadero/RADStudio12Demos#4]
According to the [documentation found by DuckDuckGo](https://docwiki.embarcadero.com/CodeExamples/Sydney/en/FireDAC.SQLite_Encryption_Sample) it should be at **Object Pascal\Database\FireDAC\Samples\DBMS Specific\SQLite\Encryption**

**Comment by checkdigits** [comment]
Some of the demos are being refreshed and are currently unavailable. Until we put up the refreshed demos please email me directly if you need this example. ian.barker@embarcadero.com

**Comment by PeterAdam** [comment]
Thank you, in the meantime I have found that the older sample is usable in Delphi 12 CE. Setting the EngineLinkage to slFDEStatic made it usable.
